#!/bin/sh

set -e

if [ `id -u` -ne 0 ]; then
    echo "Error! You must have super user privileges (root) to install the WPchk script powered by Plesk." >&2

    exit 1
fi

curl https://raw.githubusercontent.com/plesk/wpchk/master/wpchk.phar -o /usr/local/bin/wpchk

chmod +x /usr/local/bin/wpchk

echo "Success! The WPchk script powered by Plesk has been installed. Now run it with 'wpchk'."
