#!/bin/sh

set -e

if [ `id -u` -ne 0 ]; then
    echo "Error! You must have super user privileges (root) to install the WpScan script powered by Plesk." >&2

    exit 1
fi

curl https://raw.githubusercontent.com/plesk/wpscan/master/wpscan.phar -o /usr/local/bin/wpscan

chmod +x /usr/local/bin/wpscan

echo "Success! The WpScan script powered by Plesk has been installed. Now run it with 'wpscan'."
